import { BookForHeading } from "./types";

export const tableHeadings: { [key in keyof BookForHeading]: string } = {
  title: "Book title",
  name: "Author Name",
  category: "Category",
  isbn: "ISBN",
  createdAt: "Created At",
  editedAt: "Edited At",
  actions: "Actions",
};

export const bookCategories: string[] = [
  "Fiction",
  "Non-fiction",
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Romance",
  "Historical Fiction",
  "Adventure",
  "Young Adult",
  "Children's Books",
  "Graphic Novels",
  "Poetry",
  "Drama",
  "Biography",
  "Autobiography",
  "Memoir",
  "Self-help",
  "Psychology",
  "Philosophy",
  "Sociology",
  "Religion & Spirituality",
  "Politics",
  "Economics",
  "Science",
  "Technology",
  "Health & Wellness",
  "Cooking",
  "Travel",
  "Art & Photography",
  "Music",
  "Sports",
  "Hobbies & Crafts",
  "Business & Finance",
  "Law",
  "Education",
  "Reference",
  "Humor",
  "Classic",
  "Literary Fiction",
  "True Crime",
  "Paranormal",
  "Horror",
  "Science & Nature",
  "Children's Non-fiction",
  "Social Issues",
  "Environmental",
  "Military",
  "Crime",
  "Health",
  "Psychological Thriller",
  "Urban Fiction",
  "Dystopian",
  "Fairy Tales & Folklore",
  "Espionage",
  "Western",
  "Graphic Novels & Comics",
  "Anthology",
  "Short Stories",
  "Drama & Performance",
  "Textbooks",
  "Political Science"
];

